repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        types: [file]
        types_or: [html, css, scss, javascript]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.45.0
    hooks:
      - id: eslint
        files: \.(js)$
        types: [file]

  - repo: https://github.com/stylelint/pre-commit
    rev: v15.7.0
    hooks:
      - id: stylelint
        files: \.(css|scss)$
        types: [file]
